### ISSUE TITLE
Change the misleading error message in mark command

### ISSUE THREAD

**Issue by zyng233** [AY2425S1-CS2103T-F14b-3/tp#92]
![Screenshot 2024-10-20 223426](https://github.com/user-attachments/assets/6fd28e47-0e2b-4770-828e-1d4141c14a0d)

The error message did not point out the actual error where invalid input format happen

**Comment by linette-g** [comment]
Might be because the parsing detects `2024-09-15 0/Feeling sad` as the date resulting in that error message. But agree that it's a bit misleading.

**Comment by Zenkoh1** [comment]
> Might be because the parsing detects `2024-09-15 0/Feeling sad` as the date resulting in that error message. But agree that it's a bit misleading.

Yea it should be because of that, so this shld be a general problem, not just with the `mark` command. Also, changing this might be a bit hard cuz you don't know where the parameter is supposed to end.

Another example for the `edit` command

<img width="527" alt="image" src="https://github.com/user-attachments/assets/e1d9bbf1-d98a-4cae-9a1f-318683a15230">

**Comment by brendanng7** [comment]
maybe we could put the command formats below the error messages

**Comment by zyng233** [comment]
I think for marking, since we have restricted the date format, so maybe we can detect after the date.
Also, I add in the duplicate prefixes checking for mark.
![Screenshot 2024-10-21 022333](https://github.com/user-attachments/assets/650eef8f-5b3f-4e6b-933a-48943a7ae791)

**Comment by Zenkoh1** [comment]
imo since this is a general feature/bug (like with anything that has command parameters), handling like this js for the mark command might be a bit iffy

**Comment by zyng233** [comment]
okk, maybe we just handle the duplicate prefixes, and keep others unchanged
